version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    command: ["start-dev", "--import-realm"]
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: test
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_PORT: 8443
      KC_HOSTNAME_URL: http://localhost:8443/keycloak
    ports:
      - "8443:8443"
    volumes:
      - ./local/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
