sonar.projectKey=digitalservicebund_ris-cm
sonar.organization=digitalservicebund
sonar.projectName=ris-cm
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.d.ts, **/*.spec.ts, src/router.ts, src/main.ts, src/scripts/getFavicon.ts, src/stores/sessionStore.ts