name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 18 * * 3"
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  RUN_ID: ${{ github.run_id }}
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  CONTAINER_IMAGE_VERSION: ${{ github.event.pull_request.head.sha || github.sha }}
  REPORTS_REPOSITORY: digitalservicebund/ris-reports
  SLACK_CHANNEL_ID: C0471B2N86L

jobs:
  tests-and-code-quality:
    uses: ./.github/workflows/tests-and-code-quality.yml
    secrets: inherit

  audit-licenses:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .node-version
          cache: npm

      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependecies
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Audit used licenses
        run: npm run audit:licenses -- --csv --out ./license-report.csv

      - name: Upload license report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: license-reports
          retention-days: 3
          path: license-report.csv

      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  vulnerability-scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - tests-and-code-quality
      - audit-licenses
      - vulnerability-scan
    permissions:
      contents: read
      id-token: write # Required for identity challenge with sigstore/fulcio
      packages: write
    env:
      PACKAGE_NAME: ris-cm
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_VERSION }}
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          build-args: |
            SENTRY_RELEASE=ris-cm@${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true

      - name: Generate cosign vulnerability scan record
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_VERSION }}
          format: "cosign-vuln"
          output: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"

      - name: Upload cosign vulnerability scan record
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"
          path: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"
          if-no-files-found: error

      - name: Install cosign
        # Third-party action, pin to commit SHA!
        # See [https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: "v2.6.0"

      - name: Sign the published Docker image
        run: cosign sign --yes ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_VERSION }}

      - name: Attest the vulnerability scan
        run: cosign attest --yes --replace --predicate ${{ env.PACKAGE_NAME }}-vulnerabilities.json --type vuln ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_VERSION }}

      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: failure()
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  deploy-staging-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build-and-push-image
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy-job.yml
    secrets: inherit
    with:
      environment: staging

  deploy-uat-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - deploy-staging-job
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy-job.yml
    secrets: inherit
    with:
      environment: uat

  deploy-production-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - deploy-uat-job
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy-job.yml
    secrets: inherit
    with:
      environment: production

  push-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - build-and-push-image
      - vulnerability-scan
      - audit-licenses
      - tests-and-code-quality
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      # Setup
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: ${{ env.REPORTS_REPOSITORY }}
          ssh-key: ${{ secrets.REPORTS_DEPLOY_KEY }}
      - name: Setup git config
        run: |
          git config user.name "${{ github.repository }}"
          # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Checkout ris-cm repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          path: ris-cm
      # Copy ADRs into tmp folder
      - name: Copy ADRs
        run: |
          mkdir -p tmp/adr-source
          find ris-cm/doc/adr/ -type f -exec cp {} tmp/adr-source/ \;
          ls -l tmp/adr-source
      # License reports
      - name: License reports - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: license-reports
          path: tmp/license-reports/
      - name: Frontend license report - git add report
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/license-reports/license-report.csv
          destinationDir: licence-reports/frontend/ris-cm
      # ADRs
      - name: add ADRs to report
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/adr-source
          destinationDir: adr/ris-cm
          reportIsDirectory: true
          keepAllVersions: false
      # E2E test report
      - name: E2E test reports - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: e2e-test-report-chromium
          path: tmp/e2e-test-report/
      - name: E2E test reports - git add report
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/e2e-test-report/
          destinationDir: test-reports/ris-cm/e2e-tests
          reportIsDirectory: true
      # A11y test report
      - name: A11y test reports - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: a11y-test-report-chromium
          path: tmp/a11y-test-report/
      - name: A11y test reports - git add report
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/a11y-test-report/
          destinationDir: test-reports/ris-cm/a11y-tests
          reportIsDirectory: true
      # Unit test report
      - name: unit test report - download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: unit-test-report
          path: tmp/unit-test-report
      - name: unit test report - git add report
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/unit-test-report
          destinationDir: test-reports/ris-cm/unit-tests
          reportIsDirectory: true
      # Push reports
      - name: Push reports
        # we use `toJSON(...)` below to escape double quotation marks
        run: |
          git diff-index --cached --quiet HEAD ||
            git commit \
              -m "Update from ${{ github.repository }}" \
              -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" &&
            git push origin main &&
            echo "Pushed reports to ${{ github.server_url }}/${{ env.REPORTS_REPOSITORY }}" >> $GITHUB_STEP_SUMMARY
