on:
  workflow_call:
    secrets:
      SLACK_BOT_TOKEN:
        required: false
      SONAR_TOKEN:
        required: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Cache node_modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: node-modules-cache
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts
      - name: Run tests
        run: npm run test:report
      - name: Upload test report artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: unit-test-report
          path: test-results/unit-tests
          if-no-files-found: warn
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Cache node_modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: node-modules-cache
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts

      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/@playwright/test"].version' package-lock.json)" >> $GITHUB_ENV
      - name: Cache browser binaries
        id: cache-browser-binaries
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright browsers
        if: steps.cache-browser-binaries.outputs.cache-hit != 'true'
        run: |
          npx --yes playwright install --with-deps chromium

      - name: Run e2e tests
        run: npm run test:e2e
        # TODO: (Malte Laukötter, 2026-03-18) add a e2e-test run for firefox and edge as a daily task
      - name: Upload test result blobs reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ !cancelled() }}
        with:
          name: e2e-test-report-chromium
          path: ./test-results/index.html
          retention-days: 1
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  a11y-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Cache node_modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: node-modules-cache
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts

      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/@playwright/test"].version' package-lock.json)" >> $GITHUB_ENV
      - name: Cache browser binaries
        id: cache-browser-binaries
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright browsers
        if: steps.cache-browser-binaries.outputs.cache-hit != 'true'
        run: |
          npx --yes playwright install --with-deps chromium

      - name: Run a11y tests (chromium)
        run: npm run test:a11y

      - name: Upload test result blobs reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ !cancelled() }}
        with:
          name: a11y-test-report-chromium
          path: ./test-results/index.html
          retention-days: 1

      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Cache node_modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: node-modules-cache
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}
      - name: Cache style checks
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: style-check-cache
        with:
          path: .cache
          key: style-check-${{ github.ref }}-${{ github.sha }}
          # If no direct cache hit for the current commit, fallback to the latest cache
          restore-keys: |
            style-check-${{ github.ref }}-
            style-check-
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts
      - name: Check style
        run: npm run style:check
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Run coverage
        if: ${{  github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm ci --ignore-scripts
          npm run coverage
        working-directory: ./
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
        if: ${{  github.actor != 'dependabot[bot]' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.qualitygate.wait=true
      - name: Check SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@cb3ed20f9fec62b4c3b8ad9e77656c6adaade913
        if: ${{  github.actor != 'dependabot[bot]' }}
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        timeout-minutes: 3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}
